[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
